### ISSUE TITLE
uiop:run-program with string input

### ISSUE THREAD

**Issue by epipping** [michaelw/cl-dot#19]
Hi,

I was looking at how different projects on quicklisp use `uiop:run-program` and came across this snippet in cl-dot:

```common-lisp
    (uiop:run-program (list dot-path format "-o" (namestring outfile))
                      :input (make-string-input-stream dot-string)
                      :output *standard-output*)))
```
I wanted to let you know that passing input to uiop:run-program through a stream, especially one that isn't a file stream, is not very portable. But you can also pass strings directly (that's far more portable because it internally uses a file). So e.g.
```common-lisp
(uiop:run-program "cat" :input '("hello, world") :output :interactive)
```
will print "hello, world".

**Comment by marcoheisig** [comment]
Hello @epipping.  You mention that the current solution is not very portable.  I am willing to improve it, but for this I need an example of an implementation/operating system combination where the current solution causes trouble.  If I don't hear about any actual problems in the near future, I will close this issue.
