### ISSUE TITLE
Bump version, please

### ISSUE THREAD

**Issue by rpgoldman** [michaelw/cl-dot#23]
Now that we have a more extensive treatment of attributes, would it be OK to bump the `:version` in cl-dot.asd from 0.8 to 0.9?

Honestly, given the maturity of this library, I think one could bump it to 1.0, but there does seem to be an open source taboo against version numbers greater than or equal to 1! 😉

**Comment by marcoheisig** [comment]
I just bumped the version number to 0.9.
