### ISSUE TITLE
URL in README is broken

### ISSUE THREAD

**Issue by phoe** [michaelw/cl-dot#24]
http://foldr.org/~michaelw/projects/cl-dot/

![zrzut ekranu z 2019-01-04 16-31-51](https://user-images.githubusercontent.com/15045546/50695884-413c5300-103e-11e9-8aed-385cfadb5b56.png)

http://www.foldr.org/~michaelw/projects/cl-dot/ is the working URL.

**Comment by daveloyall** [comment]
Both URLs work at this time, FYI.

**Comment by phoe** [comment]
OK - this is closeable then.
