### ISSUE TITLE
dot and neato not found in path on Windows

### ISSUE THREAD

**Issue by Zulu-Inuoe** [michaelw/cl-dot#25]
It looks like on Windows, cl-dot requires dot and neato to be installed in a specific location (Program Files/ATT/Graphviz/bin/) or for the CL_DOT env vars to be defined.
I think it'd be reasonable to try and find dot on PATH, as is done on other platforms.

Thanks!

**Comment by Zulu-Inuoe** [comment]
Just ran into this again and noticed it hasn't been merged in. Any active maintainers?

**Comment by daveloyall** [comment]
[scymtym's fork](https://github.com/scymtym/cl-dot/) looks to be the most active these days. There are two branches.

**Comment by Zulu-Inuoe** [comment]
@daveloyall The latest activity here is from 2018. The fork you pointed to is from 2015. And this (@michaelw 's) fork is the one that is registered on Quicklisp

**Comment by daveloyall** [comment]
Yes, michaelw is the maintainer.  Let's call that repo upstream.  scymtym's `wip-clusters` branch contains code not yet in master on upstream.  (hm, it is labeled WIP--work in progress.) michaelw has previously merged scymtym's work into upstream.

When you use [Github's "network" feature on the cl-dot upstream repo](https://github.com/michaelw/cl-dot/network), you see the various contributions that have been made over the years (on GitHub, at least).  You should probably ignore my repo there.  It is the result of my attempt to pull in various changes from that network...  Later, michaelw pulled those same changes into his repo, so my merges are moot.  (Anyway, I'm an amateur at git and and amateur at common lisp!  I think I'll wipe my repo when I get around to it.)  Please note that when using the network feature, commits in other repos disappear from that view when they get merged into the repo you have selected as primary.

I guess I'm suggesting that if you want a more featurful `cl-dot`, you should cobble together your own and use it as a [quicklisp local project](http://blog.quicklisp.org/2018/01/the-quicklisp-local-projects-mechanism.html).

But, that's not what you want.  You want upstream to be updated.  Well, I looked at the author's github profile and read his webpage and his twitter and I don't see any Donate Now button or commentary about how or why or when he does work on `cl-dot`.  (Looks like a labor of love to me.)

**Comment by Zulu-Inuoe** [comment]
Got it, thanks for the explanation.
What I think I'll do is that when I get some free time I'll try harder to contact @michaelw , and ask if it's alright with them to take over the quicklisp pointer to this project, or otherwise ask for commit permissions on this repo so that I can maintain it if they'd rather not. 
It's definitely a labour of love and I'd like to help in improving it because it's a library I've used over the years. 

Especially thank you for pointing me at the wip-clusters branch, because that functionality is something I was thinking of adding to cl-dot myself since I need to render some subgraphs.
Once the maintainer business is sorted I'd like to review the WIP code in @scymtym 's branch to see what state it's in and see about bringing it into master so it's more generally available to people pulling in cl-dot.

And with regards to local projects - it's honestly easier to contribute to upstream projects and be able to pull them down with zero configuration (especially when working in a shared codebase) than it is to maintain my own fork and have to configure every dev machine to point to it, keep it up to date, and so on.

**Comment by michaelw** [comment]
Yup, please feel free to take over (if not already done).

**Comment by rpgoldman** [comment]
@michaelw @Zulu-Inuoe -- I wasn't quite sure what the conclusion is here: does `michaelw/cl-dot` remain the authoritative repo and @Zulu-Inuoe just get the ability to commit to it?  Or is a different repo going to become the authoritative one?

If it's the second, maybe either (a) moving to gitlab.common-lisp.net or (b) setting up a group, like `cl-dot-devs` and moving this to `github.com/cl-dot-devs/cl-dot` would be better.

That provides a more graceful path to transition than using someone's personal github space as the authoritative repo.   I agree that if we can keep using `michaelw/cl-dot/` that's best, since it is minimally upsetting.  But if we must change things, I'd suggest changing them once in a way that will remove the need for further moves in the future.

@michaelw Thanks for your time caring for cl-dot to date.

**Comment by michaelw** [comment]
I am happy to give access to the repo, but in the long run I'd suggest to make a different repo the authoritative source, so that I won't be the bottleneck for anything.

Let me know how I can help with the transition.

**Comment by rpgoldman** [comment]
@michaelw Then I think probably the best will be for @Zulu-Inuoe to set up a `cl-dot-devs` group with a shared repo, and let people in so that changes in personnel don't require further relocation of the repository.  I don't believe you can transfer ownership of this repo to that group, although I am not at all an expert on GitHub.

**Comment by Zulu-Inuoe** [comment]
Hey all.
I went ahead and did as suggested by @rpgoldman and created https://github.com/orgs/cl-dot-devs/
I invited @michaelw to be a member.
However, as I was writing this I realized that perhaps it may be better to keep the repo as-is, because I feel like the waves caused from broken url's from quicklisp et al are a bigger pain than just having it as-is, under @michaelw 's account and simply adding collaborators with permissions to maintain.

Thoughts?

**Comment by Zulu-Inuoe** [comment]
Also, I don't think this issue should have been closed, since the PR is still open (#26 ) and not merged in.

**Comment by rpgoldman** [comment]
@Zulu-Inuoe I think one thing you could do, if `michaelw` gives you access to this repo is to move development to the new repo (for the reasons mentioned above), but continue to have `michaelw/cl-dot/master` be synced with the upstream, until Quicklisp is updated, then take it down.

**Comment by michaelw** [comment]
I added @Zulu-Inuoe and @rpgoldman as collaborators.  Feel free to use the repo for as long as you need.

**Comment by Zulu-Inuoe** [comment]
@michaelw It looks like I don't have push permissions on the repo
