### ISSUE TITLE
Documentation doesn't build

### ISSUE THREAD

**Issue by daveloyall** [michaelw/cl-dot#7]
Sorry, I don't really know anything about makeinfo.

Here's a log of what I did that makes me think something is wrong.

I hope this helps.

    hobbes@metalbaby:~/quicklisp/local-projects/cl-dot/docs$ ls -al
    total 240
    drwxr-xr-x 2 hobbes hobbes  4096 Mar 20 15:57 .
    drwxrwx--- 5 hobbes hobbes  4096 Mar 20 10:31 ..
    -rw-r--r-- 1 hobbes hobbes   187 Mar 19 14:41 .gitignore
    -rw-r--r-- 1 hobbes hobbes  1534 Mar 19 14:41 Makefile
    -rw-r--r-- 1 hobbes hobbes 30315 Mar 19 14:41 manual.texi
    -rw-r--r-- 1 hobbes hobbes  2582 Mar 19 14:41 style.css
    -rw-r--r-- 1 hobbes hobbes  5621 Mar 19 14:41 test-edges.png
    -rw-r--r-- 1 hobbes hobbes 43579 Mar 19 14:41 test-lr.png
    -rw-r--r-- 1 hobbes hobbes 50213 Mar 19 14:41 test.png
    -rw-r--r-- 1 hobbes hobbes 41355 Mar 19 14:41 test-ports.png
    -rw-r--r-- 1 hobbes hobbes 35095 Mar 19 14:41 test-undir.png
    -rw-r--r-- 1 hobbes hobbes    30 Mar 20 15:55 version.texi
    hobbes@metalbaby:~/quicklisp/local-projects/cl-dot/docs$ make
    echo "@set VERSION 0.8.0-30-g01f6ac" > version.texi.tmp
    if cmp version.texi.tmp version.texi 2>/dev/null; then rm -f version.texi.tmp; else mv version.texi.tmp version.texi; fi
    makeinfo --html --css-ref style.css --no-number-sections --no-split manual.texi
    manual.texi:243: warning: @ifnottex should only appear at a line beginning (possibly involving @coderef)
    manual.texi:249: warning: @ifnottex should only appear at a line beginning (possibly involving @pcoderef)
    manual.texi:250: warning: @ifnottex should only appear at a line beginning (possibly involving @pcoderef)
    manual.texi:254: warning: @ifnottex should only appear at a line beginning (possibly involving @pcoderef)
    manual.texi:256: warning: @ifnottex should only appear at a line beginning (possibly involving @pcoderef)
    manual.texi:260: warning: @ifnottex should only appear at a line beginning (possibly involving @pcoderef)
    manual.texi:261: warning: @ifnottex should only appear at a line beginning (possibly involving @pcoderef)
    manual.texi:275: warning: @ifnottex should only appear at a line beginning (possibly involving @coderef)
    manual.texi:277: warning: @ifnottex should only appear at a line beginning (possibly involving @coderef)
    manual.texi:278: warning: @ifnottex should only appear at a line beginning (possibly involving @coderef)
    manual.texi:282: warning: @ifnottex should only appear at a line beginning (possibly involving @pcoderef)
    manual.texi:283: warning: @ifnottex should only appear at a line beginning (possibly involving @pcoderef)
    manual.texi:291: warning: @ifnottex should only appear at a line beginning (possibly involving @pcoderef)
    manual.texi:293: warning: @ifnottex should only appear at a line beginning (possibly involving @pcoderef)
    manual.texi:299: warning: @ifnottex should only appear at a line beginning (possibly involving @coderef)
    manual.texi:299: @end float seen before @code closing brace
    manual.texi:298: @end float seen before @caption closing brace
    manual.texi:303: warning: @ifnottex should only appear at a line beginning (possibly involving @coderef)
    manual.texi:307: warning: @ifnottex should only appear at a line beginning (possibly involving @pcoderef)
    manual.texi:316: warning: @ifnottex should only appear at a line beginning (possibly involving @coderef)
    manual.texi:316: @end float seen before @code closing brace
    manual.texi:315: @end float seen before @caption closing brace
    manual.texi:320: warning: @ifnottex should only appear at a line beginning (possibly involving @coderef)
    manual.texi:335: warning: @ifnottex should only appear at a line beginning (possibly involving @coderef)
    manual.texi:336: warning: @ifnottex should only appear at a line beginning (possibly involving @coderef)
    manual.texi:335: @code missing close brace
    manual.texi:344: warning: @ifnottex should only appear at a line beginning (possibly involving @pcoderef)
    manual.texi:345: warning: @ifnottex should only appear at a line beginning (possibly involving @pcoderef)
    manual.texi:353: warning: @ifnottex should only appear at a line beginning (possibly involving @pcoderef)
    manual.texi:358: warning: @ifnottex should only appear at a line beginning (possibly involving @pcoderef)
    manual.texi:360: warning: @ifnottex should only appear at a line beginning (possibly involving @pcoderef)
    manual.texi:366: warning: @ifnottex should only appear at a line beginning (possibly involving @coderef)
    manual.texi:366: @end float seen before @code closing brace
    manual.texi:366: @end float seen before @caption closing brace
    manual.texi:385: warning: @ifnottex should only appear at a line beginning (possibly involving @pcoderef)
    manual.texi:386: warning: @ifnottex should only appear at a line beginning (possibly involving @pcoderef)
    manual.texi:395: warning: @ifnottex should only appear at a line beginning (possibly involving @pcoderef)
    manual.texi:396: warning: @ifnottex should only appear at a line beginning (possibly involving @pcoderef)
    manual.texi:400: warning: @ifnottex should only appear at a line beginning (possibly involving @pcoderef)
    manual.texi:401: warning: @ifnottex should only appear at a line beginning (possibly involving @pcoderef)
    manual.texi:404: warning: @ifnottex should only appear at a line beginning (possibly involving @pcoderef)
    manual.texi:409: warning: @ifnottex should only appear at a line beginning (possibly involving @pcoderef)
    manual.texi:410: warning: @ifnottex should only appear at a line beginning (possibly involving @pcoderef)
    manual.texi:423: warning: @ifnottex should only appear at a line beginning (possibly involving @pcoderef)
    manual.texi:425: warning: @ifnottex should only appear at a line beginning (possibly involving @pcoderef)
    manual.texi:431: warning: @ifnottex should only appear at a line beginning (possibly involving @coderef)
    manual.texi:431: @end float seen before @code closing brace
    manual.texi:430: @end float seen before @caption closing brace
    manual.texi:487: warning: @ifnothtml should only appear at a line beginning (possibly involving @keyword)
    manual.texi:487: warning: @html should only appear at a line beginning (possibly involving @keyword)
    manual.texi:489: warning: @ifnothtml should only appear at a line beginning (possibly involving @keyword)
    manual.texi:489: warning: @html should only appear at a line beginning (possibly involving @keyword)
    manual.texi:521: warning: @ifnottex should only appear at a line beginning (possibly involving @coderef)
    manual.texi:524: warning: @ifnottex should only appear at a line beginning (possibly involving @coderef)
    manual.texi:536: warning: @ifnottex should only appear at a line beginning (possibly involving @coderef)
    manual.texi:544: warning: @ifnottex should only appear at a line beginning (possibly involving @coderef)
    manual.texi:549: warning: @ifnottex should only appear at a line beginning (possibly involving @coderef)
    manual.texi:592: warning: @ifnottex should only appear at a line beginning (possibly involving @coderef)
    manual.texi:604: warning: @ifnottex should only appear at a line beginning (possibly involving @coderef)
    manual.texi:721: warning: @ifnothtml should only appear at a line beginning (possibly involving @keyword)
    manual.texi:721: warning: @html should only appear at a line beginning (possibly involving @keyword)
    manual.texi:723: warning: @ifnottex should only appear at a line beginning (possibly involving @coderef)
    manual.texi:727: warning: @ifnottex should only appear at a line beginning (possibly involving @coderef)
    manual.texi:728: warning: @ifnottex should only appear at a line beginning (possibly involving @coderef)
    manual.texi:729: warning: @ifnottex should only appear at a line beginning (possibly involving @coderef)
    manual.texi:735: warning: @ifnothtml should only appear at a line beginning (possibly involving @keyword)
    manual.texi:735: warning: @html should only appear at a line beginning (possibly involving @keyword)
    manual.texi:754: warning: @ifnothtml should only appear at a line beginning (possibly involving @keyword)
    manual.texi:754: warning: @html should only appear at a line beginning (possibly involving @keyword)
    manual.texi:761: warning: @ifnothtml should only appear at a line beginning (possibly involving @keyword)
    manual.texi:761: warning: @html should only appear at a line beginning (possibly involving @keyword)
    manual.texi:776: warning: @ifnottex should only appear at a line beginning (possibly involving @coderef)
    manual.texi:781: warning: @ifnothtml should only appear at a line beginning (possibly involving @keyword)
    manual.texi:781: warning: @html should only appear at a line beginning (possibly involving @keyword)
    manual.texi:782: warning: @ifnothtml should only appear at a line beginning (possibly involving @keyword)
    manual.texi:782: warning: @html should only appear at a line beginning (possibly involving @keyword)
    manual.texi:786: warning: @ifnottex should only appear at a line beginning (possibly involving @coderef)
    manual.texi:798: warning: @ifnottex should only appear at a line beginning (possibly involving @coderef)
    manual.texi:801: warning: @ifnottex should only appear at a line beginning (possibly involving @coderef)
    manual.texi:184: warning: multiple @menu
    Makefile:39: recipe for target 'cl-dot.html' failed
    make: *** [cl-dot.html] Error 1
    hobbes@metalbaby:~/quicklisp/local-projects/cl-dot/docs$ less Makefile 
    hobbes@metalbaby:~/quicklisp/local-projects/cl-dot/docs$ makeinfo --version
    makeinfo (GNU texinfo) 5.2
    
    Copyright (C) 2013 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.

**Comment by guicho271828** [comment]
this is due to incompatibility between texinfo 5 and its older versions.

**Comment by guicho271828** [comment]
fixed in #9 .

**Comment by michaelw** [comment]
closed by #9
